# Generated by Django 5.2.1 on 2025-05-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_lead', models.CharField(max_length=45)),
                ('lead_number', models.CharField(max_length=50)),
                ('team_member', models.CharField(max_length=200)),
                ('postingDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='incident_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=70, null=True)),
                ('Postingdate', models.DateTimeField(auto_now_add=True)),
                ('AssignedTime', models.CharField(max_length=150, null=True)),
                ('UpdationDate', models.DateTimeField(null=True)),
                ('AssignTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.add_team')),
            ],
        ),
        migrations.CreateModel(
            name='incident_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=75, null=True)),
                ('remark', models.CharField(max_length=75, null=True)),
                ('PostingDate', models.DateTimeField(auto_now_add=True)),
                ('incidentreport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.incident_report')),
            ],
        ),
    ]
