# Generated by Django 5.2.1 on 2025-05-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_incident_report_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident_report',
            name='image',
        ),
    ]
