# Generated by Django 5.2.1 on 2025-05-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_incident_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_images/'),
        ),
    ]
